### ISSUE TITLE
failure to load the library with cabal

### ISSUE THREAD

**Issue by acapi** [slpopejoy/fadno-xml#1]
Windows PowerShell
Copyright (C) Microsoft Corporation. Tutti i diritti sono riservati.

PS C:\Users\user> cabal --http-transport=plain-http update
Downloading the latest package list from hackage.haskell.org
PS C:\Users\user> cabal install fadno-xml
Resolving dependencies...
cabal.exe: Could not resolve dependencies:
trying: fadno-xml-1.1.0 (user goal)
next goal: base (dependency of fadno-xml-1.1.0)
rejecting: base-4.10.1.0/installed-4.1... (conflict: fadno-xml => base==4.9.*)
rejecting: base-4.10.1.0, base-4.10.0.0, base-4.9.1.0, base-4.9.0.0,
base-4.8.2.0, base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1,
base-4.7.0.0, base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0,
base-4.4.1.0, base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2,
base-4.2.0.1, base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2,
base-3.0.3.1 (constraint from non-upgradeable package requires installed
instance)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, fadno-xml

**Comment by sirlensalot** [comment]
v1.1.1 updates deps to support base 4.10
